### PR TITLE
Changed source of the confd binary.

### PR DESCRIPTION
**Pull request by bronger**
I think it makes this image much more trustworthy if it does not include a binary blob.  Besides, it is suboptimal to have a binary in a Git repo in the first place.  Thus, I suggest to build confd in a two-step Dockerfile.

### CODE REVIEW

**Comment by sjiveson** [comment]
Hey,

Thank you, I like this a lot. I'll give it a run through ~~tonight~~~this weekend and if that goes well I'll merge it.

**Comment by sjiveson** [comment]
OK, it built just fine which is great. However, it increased the image size by approx. 20MB, any idea why? Also, is there a reason your are pinning confd to v0.14?

**Comment by bronger** [comment]
No idea.  I would have thought just the binary is copied into the image, as it has been before.  Just that the source is different.  Very odd.

I pinned for no particular reason.  Sometimes, new versions cause incompatibilities.  It depends on how confd is being developed.  I don't have experience with this program.

**Comment by bronger** [comment]
https://github.com/kelseyhightower/confd/blob/master/docs/installation.md#build-for-your-image-using-multi-stage-build uses `go install` instead of `make`. Possibly one could give this a try.

**Comment by sjiveson** [comment]
I gave it a go, it didn't help. I'll experiment further later today. In any case, its still a relatively small image so I think its still worth doing.

**Comment by sjiveson** [comment]
I think its mostly just the confd binary being much bigger with v0.16. I'll move back to 0.14 and then get this merged

**Comment by sjiveson** [comment]
OK, I've done it the other way using the kelsey example you linked to and dropping to v0.14. Its still bigger but worth the overhead I think. I'll close this off. Have mentioned in the readme it was your idea - thanks again.

**Pull request closed without merging**
