### PR TITLE
(feat): added dynamic multiple shared directories

### PR DESCRIPTION
**Pull request by g0blin79**
Signed-off-by: Daniele Piaggesi <daniele.piaggesi@bonsaimeme.com>

### CODE REVIEW

**Comment by colearendt** [comment]
Related in some measure to #23? (which allows arbitrary directory exports through the `runcmd`)

**Comment by ghost** [comment]
This pr is better than fixed parameters _2

**Comment by groundnuty** [comment]
any chance to accept this?

**Comment by toastbrotch** [comment]
i see extra-dirs having different

**Pull request closed without merging**
